# Generated by Django 4.2.7 on 2023-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('month', models.TextField()),
                ('image', models.ImageField(upload_to='pic')),
                ('subscript', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
